# Import the libraries

In [165]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [166]:
pip install lazypredict

Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip available: 22.3.1 -> 23.3.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [167]:
from lazypredict.Supervised import LazyClassifier


# Import the dataset

In [168]:
dataset = pd.read_csv('D:\ml\practice\Classification\emails.csv')
X = dataset.iloc[:,0].values
y = dataset.iloc[:,-1].values

# Split the dataset into train and test set

In [169]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.5,random_state=0)

In [170]:
print(X_train)

['Subject: a few comments  john ,  happy new year . i hope the first few weeks of this year will see the  completed paper .  i am sending you the last version of the paper i have received with a few  comments ( in red ) . i think it makes sense to discuss the paper over the  phone . i have a number of more detailed comments .  vince  - enron transformation paperl 2 _ 17 _ 00 _ vk . doc'
 'Subject: alliance info alert : richardson and ferc orders  dear generation / power marketing executive :  the following are summaries of two significant activities that occurred  friday , december 15  1 . energy secretary richardson issuance of an emergency order .  ( richardson \' s statement and fpa section 202 ( c ) order is posted on doe \' s  web site at :  http : / / www . energy . gov / hqpress / releaseso 0 / decpr / pro 0309 . html )  2 . ferc \' s 12 / 15 / 00 final order to fix california wholesale markets  ( ferc \' s order can be viewed at  california supplies ordered by richardson  o ric

In [171]:
print(y_train)

[0 0 1 ... 0 0 0]


In [172]:
print(X_test)

["Subject: re : comments  fyi .  - - - - - - - - - - - - - - - - - - - - - - forwarded by rakesh bharati / na / enron on 03 / 27 / 2001  07 : 43 pm - - - - - - - - - - - - - - - - - - - - - - - - - - -  sheridan titman on 03 / 27 / 2001 06 : 46 : 31 pm  to : rakesh . bharati @ enron . com  cc :  subject : re : comments  rakesh :  thanks for your input . they are quite useful for helping me clarify my own  thinking . the following are my responses to your comments and  clarifications . the * * ed paragraphs are from me and the others are from you .  1 . the money is being set aside to avoid negative values . it is not clear  if you mean the values of the cash flow or the pv at the node . anyhow , we  shall be setting aside money not just for that specific node but all nodes  at that cross - section of time as the risk - free asset pays in all states of  nature . this will have to be done every time there is a negative  realization . thus , for the typical project we have , the value of 

In [173]:
print(y_test)

[0 0 1 ... 1 0 1]


In [174]:
dataset.dtypes

text    object
spam     int64
dtype: object

# Feature Scaling

In [175]:
from sklearn.feature_extraction.text import TfidfVectorizer
vectorization = TfidfVectorizer()
X_train  = vectorization.fit_transform(X_train)
X_test = vectorization.transform(X_test)

In [176]:
# from sklearn.feature_extraction.text import TfidfVectorizer
# feature_extraction = TfidfVectorizer(min_df=1)
# # min_df is minimum woords is 1 ie words should be greater then 1\
# # stop_words english means doesnot include is are am etc.
# # all the letter converted into lowercase
# X_train = feature_extraction.fit_transform(X_train)
# X_test = feature_extraction.transform(X_test)
# y_train = y_train.astype('int')
# y_test = y_train.astype('int')

In [177]:
print(X_test)

  (0, 26719)	0.02344341807919635
  (0, 26634)	0.024010979334606736
  (0, 26625)	0.04881920948862304
  (0, 26587)	0.01451298280091108
  (0, 26584)	0.025392347472134272
  (0, 26416)	0.031206206904746816
  (0, 26285)	0.030412885659009157
  (0, 26203)	0.052597443488532854
  (0, 26164)	0.023857530374632858
  (0, 26128)	0.04249041835212227
  (0, 26127)	0.03377722113298208
  (0, 26119)	0.027485443597581687
  (0, 26116)	0.05771595123490007
  (0, 26104)	0.020457749740214637
  (0, 25960)	0.1089506075498489
  (0, 25950)	0.020434799117794163
  (0, 25907)	0.029953764262644234
  (0, 25867)	0.035275026599796394
  (0, 25734)	0.1252834124741042
  (0, 25633)	0.006708669860368969
  (0, 25553)	0.010518579533608062
  (0, 25434)	0.03249357118773251
  (0, 25433)	0.13784836042450335
  (0, 25431)	0.02616778563021736
  (0, 25410)	0.06442546525623649
  :	:
  (2863, 16776)	0.17732683100796334
  (2863, 16107)	0.09018174910375772
  (2863, 15446)	0.28322145492422335
  (2863, 15434)	0.09067468634551719
  (2863, 14047

In [178]:
print(X_train)

  (0, 8636)	0.10754455287029928
  (0, 25708)	0.22022213658210266
  (0, 0)	0.08884065918057905
  (0, 468)	0.10888043883675577
  (0, 18154)	0.24151598980897512
  (0, 24616)	0.21548654500339554
  (0, 9581)	0.055114413587572665
  (0, 25633)	0.05243544737592512
  (0, 8158)	0.1576480310876135
  (0, 16537)	0.07779110632374371
  (0, 17372)	0.09592773767133021
  (0, 18653)	0.0941867315376461
  (0, 17966)	0.092780701170139
  (0, 8464)	0.10957081702413558
  (0, 24404)	0.03349022882897863
  (0, 21904)	0.14655750744643814
  (0, 15500)	0.1438844712679046
  (0, 13660)	0.0525443469456563
  (0, 24220)	0.09592773767133021
  (0, 20312)	0.18173658614294247
  (0, 12947)	0.04127450979292047
  (0, 26285)	0.047541861463288496
  (0, 20223)	0.10305270195005836
  (0, 12041)	0.09215136856164713
  (0, 25547)	0.12013166312224437
  :	:
  (2863, 19507)	0.11781737170503623
  (2863, 1930)	0.08886713654270359
  (2863, 10848)	0.14876695054454595
  (2863, 18853)	0.04774499438662345
  (2863, 16954)	0.07169176734839831
  (2

# Train the naive_bayes model on training set

In [179]:
from sklearn.naive_bayes import GaussianNB
classifier = GaussianNB()
classifier.fit(X_train.toarray(),y_train)

GaussianNB()

# Predicting a new result

In [183]:
input = " financial engineering invoice # 2001 - m 608  connie :  in response to your email to vince kaminski of 3 / 19 / 01 , the subject invoice  was sent to our accounting dept . for payment on february 25 , 2001 . we  did not need the spav maintenance , so we deducted $ 1 , 600 . 00 . did you  receive a payment in the amount of $ 4100 . 00 that could possibly have been  payment for this invoice ?  i have left a message for our accounting dept . to see exactly when the invoice  was paid and the check number . as soon as i hear from them i will left you  know .  best regards ,  shirley crenshaw  administrative coordinator  enron research group  713 - 853 - 5290  email : shirley . crenshaw @ enron . com"
input_vector = vectorization.transform([input])
prediction = classifier.predict(input_vector.toarray())
if prediction[0] == 1:
    print("The email is spam")
else:
    print("The email is not spam")

The email is not spam


# Predicting a test result

In [181]:
y_pred = classifier.predict(X_test.toarray())
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[0 0]
 [0 0]
 [1 1]
 ...
 [1 1]
 [0 0]
 [1 1]]


# Confusion matrix

In [182]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test,y_pred)
print(cm)
accuracy_score(y_test,y_pred)

[[2154   17]
 [ 137  556]]


0.9462290502793296